[package]
name = "ip-address-distance-correlation"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
tokio-ping = "*"
tokio = "*"
futures = "*"
